# Generated by Django 5.1.3 on 2024-11-14 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usersubscription_user_subscriptions'),
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=1990, verbose_name='Цена (в рублях)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Кол-во дней')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vending.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
