# Generated by Django 5.1.3 on 2024-11-14 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_basesubscription_subscriptionpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Описание')),
                ('days', models.PositiveIntegerField(verbose_name='Кол-во дней')),
                ('cups', models.PositiveIntegerField(verbose_name='Кол-во чашек в день')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (в рублях)')),
            ],
        ),
        migrations.DeleteModel(
            name='BaseSubscription',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='price',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='today_cups',
            field=models.PositiveIntegerField(default=2, verbose_name='Осталось чашек на сегодня'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='account.subscriptiontariff'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='account.subscriptiontariff'),
        ),
    ]
