# Generated by Django 5.1.3 on 2024-11-14 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_subscriptiontariff_delete_basesubscription_and_more'),
        ('vending', '0004_subscriptiontariff_alter_place_tariffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='vending.subscriptiontariff'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vending.subscriptiontariff'),
        ),
        migrations.DeleteModel(
            name='SubscriptionTariff',
        ),
    ]
