# Generated by Django 5.1.3 on 2024-11-15 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_usersubscription_tariff_and_more"),
        ("vending", "0006_alter_place_options_place_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersubscription",
            options={
                "ordering": ["expire_date"],
                "verbose_name": "абонемент",
                "verbose_name_plural": "Абонементы пользователя",
            },
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата платежа"),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="account.usersubscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="vending.place",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="tariff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="vending.subscriptiontariff",
                verbose_name="Тариф",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriptions",
                to="vending.place",
                verbose_name="Автомат",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriptions",
                to="vending.subscriptiontariff",
                verbose_name="Тариф",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
