# Generated by Django 5.1.3 on 2024-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_usersubscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="price",
            field=models.PositiveIntegerField(default=1990, verbose_name="Стоимость"),
            preserve_default=False,
        ),
    ]
