# Generated by Django 5.1.3 on 2024-11-15 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_subscriptionpayment_price"),
        ("vending", "0008_alter_place_address_alter_place_tariffs_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionpayment",
            options={"verbose_name": "платёж", "verbose_name_plural": "Платежи"},
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="vending.place",
                verbose_name="Место",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="account.usersubscription",
                verbose_name="Абонемент",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
