# Generated by Django 5.1.3 on 2024-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("user_agreement", "Пользовательское соглашение"),
                    ("public_offer", "Публичная оферта"),
                    ("privacy_policy", "Политика обработки персональных данных"),
                ],
                unique=True,
                verbose_name="Тип документа",
            ),
        ),
    ]
