# Generated by Django 5.1.3 on 2024-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="invoice_id",
            field=models.CharField(
                blank=True, max_length=17, null=True, verbose_name="ID счёта"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="payment_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL для оплаты"),
        ),
    ]
