# Generated by Django 5.1.3 on 2024-11-19 16:11
from uuid import uuid4
from django.db import migrations, models


def set_payment_uuids(apps, schema_editor):
    SubscriptionPayment = apps.get_model("account", "SubscriptionPayment")
    for obj in SubscriptionPayment.objects.all():
        obj.uuid = uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_subscriptionpayment_invoice_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionpayment",
            name="invoice_id",
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="uuid",
            field=models.UUIDField(blank=True, null=True, verbose_name="UUID платежа"),
        ),
        migrations.RunPython(set_payment_uuids),
    ]
