# Generated by Django 5.1.3 on 2024-11-19 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_remove_subscriptionpayment_invoice_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID платежа",
            ),
        ),
    ]
