# Generated by Django 5.1.3 on 2024-11-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_subscriptionpayment_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("success", "Успешно"),
                    ("failed", "Неудачно"),
                ],
                default="success",
                verbose_name="Статус",
            ),
            preserve_default=False,
        ),
    ]
