# Generated by Django 5.1.3 on 2024-11-21 11:09

from django.db import migrations, models


def set_invoice_id(apps, schema_editor):
    SubscriptionPayment = apps.get_model("account", "SubscriptionPayment")
    for payment in SubscriptionPayment.objects.all():
        if payment.payment_url:
            payment.invoice_id = payment.payment_url.split("/")[-2]
            payment.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0015_subscriptionpayment_email_subscriptionpayment_phone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="invoice_id",
            field=models.CharField(blank=True, null=True, verbose_name="Номер счёта"),
        ),
        migrations.RunPython(set_invoice_id),
    ]
