# Generated by Django 5.1.3 on 2024-11-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_subscriptionpayment_invoice_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="expiry_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Оплатить до"
            ),
        ),
    ]
