# Generated by Django 5.1.3 on 2024-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_subscriptionpayment_expiry_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("success", "Успешно"),
                    ("expired", "Просрочен"),
                ],
                verbose_name="Статус",
            ),
        ),
    ]
