# Generated by Django 5.1.3 on 2024-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_subscriptionpayment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="opt_in_consent",
            field=models.BooleanField(
                default=False, verbose_name="Согласие на рассылку"
            ),
        ),
    ]
