# Generated by Django 5.1.3 on 2024-11-29 11:16

import django.db.models.deletion
from django.db import migrations, models


def set_partner(apps, schema_editor):
    SubscriptionPayment = apps.get_model("account", "SubscriptionPayment")
    for obj in SubscriptionPayment.objects.all():
        obj.partner = obj.place.partner
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_subscriptionpayment_opt_in_consent"),
        ("vending", "0019_drinkhistory_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="partner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="vending.partner",
                verbose_name="Партнёр",
            ),
        ),
        migrations.RunPython(set_partner),
    ]
