# Generated by Django 5.1.3 on 2024-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_subscriptionpayment_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("success", "Успешно"),
                    ("expired", "Просрочен"),
                ],
                default="pending",
                verbose_name="Статус",
            ),
        ),
    ]
