# Generated by Django 5.1.3 on 2024-12-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_alter_subscriptionpayment_status"),
        ("vending", "0021_alter_drinkhistory_drink_alter_drinkhistory_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="tariff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriptions",
                to="vending.subscriptiontariff",
                verbose_name="Тариф",
            ),
        ),
    ]
