# Generated by Django 5.1.3 on 2025-01-04 15:33

import django.contrib.auth.validators
from django.db import migrations, models
from core.utils.random_string import generate_random_string


def set_default_username(apps, schema_editor):
    User = apps.get_model("account", "User")
    for obj in User.objects.all():
        if obj.username is None or obj.username == "":
            obj.username = f"user_{generate_random_string()}"
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_alter_user_username"),
    ]

    operations = [
        migrations.RunPython(set_default_username),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
