# Generated by Django 5.1.3 on 2024-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_subscriptiontariff_delete_basesubscription_and_more'),
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tariffs',
            field=models.ManyToManyField(blank=True, related_name='places', to='account.subscriptiontariff'),
        ),
    ]
