# Generated by Django 5.1.3 on 2024-11-14 13:45

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0003_alter_place_tariffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Описание')),
                ('days', models.PositiveIntegerField(verbose_name='Кол-во дней')),
                ('cups', models.PositiveIntegerField(verbose_name='Кол-во чашек в день')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (в рублях)')),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='tariffs',
            field=models.ManyToManyField(blank=True, default=django.db.models.manager.BaseManager.all, related_name='places', to='vending.subscriptiontariff'),
        ),
    ]
