# Generated by Django 5.1.3 on 2024-11-15 12:00

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0004_subscriptiontariff_alter_place_tariffs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["address"],
                "verbose_name": "место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptiontariff",
            options={
                "verbose_name": "тариф",
                "verbose_name_plural": "Тарифы абонементов",
            },
        ),
        migrations.AlterField(
            model_name="place",
            name="tariffs",
            field=models.ManyToManyField(
                blank=True,
                default=django.db.models.manager.BaseManager.all,
                related_name="places",
                to="vending.subscriptiontariff",
            ),
        ),
    ]
