# Generated by Django 5.1.3 on 2024-11-15 14:34

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vending",
            "0005_alter_place_options_alter_subscriptiontariff_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["address"],
                "verbose_name": "автомат",
                "verbose_name_plural": "Автоматы",
            },
        ),
        migrations.AddField(
            model_name="place",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="subscriptiontariff",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="place",
            name="tariffs",
            field=models.ManyToManyField(
                blank=True,
                default=django.db.models.manager.BaseManager.all,
                related_name="places",
                to="vending.subscriptiontariff",
            ),
        ),
    ]
