# Generated by Django 5.1.3 on 2024-11-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0006_alter_place_options_place_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="tariffs",
            field=models.ManyToManyField(
                blank=True, related_name="places", to="vending.subscriptiontariff"
            ),
        ),
    ]
