# Generated by Django 5.1.3 on 2024-11-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0007_alter_place_tariffs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес автомата"),
        ),
        migrations.AlterField(
            model_name="place",
            name="tariffs",
            field=models.ManyToManyField(
                blank=True,
                related_name="places",
                to="vending.subscriptiontariff",
                verbose_name="Доступные тарифы",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontariff",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название тарифа"),
        ),
    ]
