# Generated by Django 5.1.3 on 2024-11-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0008_alter_place_address_alter_place_tariffs_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127, verbose_name="Город")),
            ],
            options={
                "verbose_name": "город",
                "verbose_name_plural": "Города",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="place",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="vending.city",
                verbose_name="Город",
            ),
        ),
    ]
