# Generated by Django 5.1.3 on 2024-11-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0009_city_place_name_place_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="tariffs",
        ),
    ]
