# Generated by Django 5.1.3 on 2024-11-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0010_remove_place_tariffs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=127, verbose_name="Название партнёра"),
                ),
            ],
            options={
                "verbose_name": "партнёра",
                "verbose_name_plural": "Партнёры",
            },
        ),
        migrations.AddField(
            model_name="place",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="vending.partner",
                verbose_name="Партнёр",
            ),
        ),
    ]
