# Generated by Django 5.1.3 on 2024-11-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0011_partner_place_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrinkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название напитка"
                    ),
                ),
            ],
            options={
                "verbose_name": "напиток",
                "verbose_name_plural": "Напитки",
            },
        ),
        migrations.CreateModel(
            name="DrinkVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume_ml", models.PositiveIntegerField(verbose_name="Объём (мл)")),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "drink_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="vending.drinktype",
                        verbose_name="Напиток",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объёмы напитков",
                "unique_together": {("drink_type", "volume_ml")},
            },
        ),
        migrations.AddField(
            model_name="place",
            name="drinks",
            field=models.ManyToManyField(
                null=True,
                related_name="places",
                to="vending.drinkvolume",
                verbose_name="Доступные напитки",
            ),
        ),
    ]
