# Generated by Django 5.1.3 on 2024-11-18 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0012_drinktype_drinkvolume_place_drinks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drinkvolume",
            options={"verbose_name": "объём", "verbose_name_plural": "Объёмы напитков"},
        ),
        migrations.AlterField(
            model_name="place",
            name="drinks",
            field=models.ManyToManyField(
                null=True,
                related_name="places",
                to="vending.drinkvolume",
                verbose_name="Меню",
            ),
        ),
        migrations.CreateModel(
            name="DrinkHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drink",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="vending.drinkvolume",
                        verbose_name="Напиток",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drink_history",
                        to="vending.place",
                        verbose_name="Автомат",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drink_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
