# Generated by Django 5.1.3 on 2024-11-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0013_alter_drinkvolume_options_alter_place_drinks_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drinkhistory",
            options={"verbose_name": "заказ", "verbose_name_plural": "История заказов"},
        ),
        migrations.AlterField(
            model_name="drinkhistory",
            name="purchased_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата покупки"),
        ),
    ]
