# Generated by Django 5.1.3 on 2024-11-19 11:31

from django.db import migrations, models


def generate_qr_codes(apps, schema_editor):
    # Получаем модель через apps.get_model
    Place = apps.get_model("vending", "Place")
    for place in Place.objects.all():
        if not place.qr_code:
            place.generate_qr_code()
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0014_alter_drinkhistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="place",
            name="drinks",
            field=models.ManyToManyField(
                blank=True,
                related_name="places",
                to="vending.drinkvolume",
                verbose_name="Меню",
            ),
        ),
        migrations.RunPython(generate_qr_codes),
    ]
