# Generated by Django 5.1.3 on 2024-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0015_place_qr_code_alter_place_drinks"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="partner_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID партнёра"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AddField(
            model_name="place",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
        migrations.AddField(
            model_name="place",
            name="terminal_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID терминала"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Адрес автомата"
            ),
        ),
    ]
