# Generated by Django 5.1.3 on 2024-11-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0016_partner_partner_id_place_latitude_place_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendistaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Логин"
                    ),
                ),
                ("password", models.CharField(max_length=32, verbose_name="Пароль")),
                ("token", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "verbose_name": "аккаунт",
                "verbose_name_plural": "Аккаунты Vendista",
            },
        ),
    ]
