# Generated by Django 5.1.3 on 2024-11-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0017_vendistaaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="vendista_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminals",
                to="vending.vendistaaccount",
                verbose_name="Аккаунт Vendista",
            ),
        ),
    ]
