# Generated by Django 5.1.3 on 2024-11-29 11:16

import django.db.models.deletion
from django.db import migrations, models


def set_partner(apps, schema_editor):
    DrinkHistory = apps.get_model("vending", "DrinkHistory")
    for obj in DrinkHistory.objects.all():
        obj.partner = obj.place.partner
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0018_place_vendista_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="drinkhistory",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drink_history",
                to="vending.partner",
                verbose_name="Партнёр",
            ),
        ),
        migrations.RunPython(set_partner),
    ]
