# Generated by Django 5.1.3 on 2024-11-29 11:48

from django.db import migrations, models


def set_price(apps, schema_editor):
    DrinkHistory = apps.get_model("vending", "DrinkHistory")
    for obj in DrinkHistory.objects.all():
        obj.price = obj.drink.price
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0019_drinkhistory_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="drinkhistory",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Стоимость"
            ),
        ),
        migrations.RunPython(set_price),
    ]
