# Generated by Django 5.1.3 on 2024-11-29 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0020_drinkhistory_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="drinkhistory",
            name="drink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="vending.drinkvolume",
                verbose_name="Напиток",
            ),
        ),
        migrations.AlterField(
            model_name="drinkhistory",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drink_history",
                to="vending.place",
                verbose_name="Автомат",
            ),
        ),
        migrations.AlterField(
            model_name="drinkhistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drink_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
