# Generated by Django 5.1.3 on 2024-12-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0021_alter_drinkhistory_drink_alter_drinkhistory_place_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="drinks",
        ),
        migrations.AddField(
            model_name="drinktype",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drinks",
                to="vending.place",
                verbose_name="Автомат",
            ),
        ),
    ]
