# Generated by Django 5.1.3 on 2024-12-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0022_remove_place_drinks_drinktype_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drinktype",
            options={"verbose_name": "напиток", "verbose_name_plural": "Меню напитков"},
        ),
    ]
