# Generated by Django 5.1.3 on 2024-12-17 13:47

from django.db import migrations, models


def set_drink_name(apps, schema_editor):
    DrinkHistory = apps.get_model("vending", "DrinkHistory")
    for obj in DrinkHistory.objects.all():
        if obj.drink:
            obj.drink_name = obj.drink.name
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0023_alter_drinktype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="drinkhistory",
            name="drink_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Напиток"
            ),
        ),
        migrations.RunPython(set_drink_name),
        migrations.RemoveField(
            model_name="drinkhistory",
            name="drink",
        ),
    ]
