# Generated by Django 5.1.3 on 2024-12-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0024_remove_drinkhistory_drink_drinkhistory_drink_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drinktype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название напитка"),
        ),
    ]
