# Generated by Django 5.1.3 on 2024-11-13 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'обращение', 'verbose_name_plural': 'Обращения в поддержку'},
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
