# Generated by Django 5.1.3 on 2024-11-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_alter_supportrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="viewed",
            field=models.BooleanField(default=False, verbose_name="Просмотрено"),
        ),
    ]
